version: "3.8"

services:
  app:
    container_name: base_converter-dev
    image: base_converter-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/base_converter/src
    ports:
      - 5173:5173